# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
format = '$os$all'

[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Windows = ''
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

[username]
disabled = false
show_always = false
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '

[hostname]
disabled = false
ssh_only = true
format = 'on [$hostname](bold yellow) '

[directory]
truncation_length = 12
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

[git_branch]
disabled = false
symbol = ''

[git_status]
disabled = false

[pulumi]
disabled = false
format = 'via [$symbol$stack]($style) '

[golang]
disabled = true
format = '[$symbol($version)]($style) '
symbol = ' '

[kubernetes]
disabled = false

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[aws]
disabled = true
symbol = '🅰 '

[nodejs]
disabled = false
format = '[$symbol($version) ]($style)'
version_format='${raw}'

[ruby]
disabled = true

[terraform]
disabled = true
